// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2fcCKyhe1hjHglDbaVj2Ki2pwySS1GWc',
    appId: '1:1046076081470:web:c6dc6aaf6e9bd11c68186f',
    messagingSenderId: '1046076081470',
    projectId: 'kariger-da3ac',
    authDomain: 'kariger-da3ac.firebaseapp.com',
    storageBucket: 'kariger-da3ac.firebasestorage.app',
    measurementId: 'G-3TZED4HXJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGv623hEb-k0ryUzmaXSTI2i9hOwFSJpU',
    appId: '1:1046076081470:android:eda7ae70617510f668186f',
    messagingSenderId: '1046076081470',
    projectId: 'kariger-da3ac',
    storageBucket: 'kariger-da3ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd-HX_ofJVl9KLHNiCrVsneEGRAlNrxIw',
    appId: '1:1046076081470:ios:cc6fea113a90d1e568186f',
    messagingSenderId: '1046076081470',
    projectId: 'kariger-da3ac',
    storageBucket: 'kariger-da3ac.firebasestorage.app',
    iosBundleId: 'com.example.employerKarigerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd-HX_ofJVl9KLHNiCrVsneEGRAlNrxIw',
    appId: '1:1046076081470:ios:cc6fea113a90d1e568186f',
    messagingSenderId: '1046076081470',
    projectId: 'kariger-da3ac',
    storageBucket: 'kariger-da3ac.firebasestorage.app',
    iosBundleId: 'com.example.employerKarigerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2fcCKyhe1hjHglDbaVj2Ki2pwySS1GWc',
    appId: '1:1046076081470:web:9dd61e0f9839821e68186f',
    messagingSenderId: '1046076081470',
    projectId: 'kariger-da3ac',
    authDomain: 'kariger-da3ac.firebaseapp.com',
    storageBucket: 'kariger-da3ac.firebasestorage.app',
    measurementId: 'G-0KK0009K26',
  );
}
